[package]
name = "acme-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
ulid = "1.1.0"

[dev-dependencies]
rstest = "0.18.2"
